config/routes.rb
Rails.application.routes.draw do
  get 'sales/new'
  post 'sales', to: 'sales#create'
  get 'sales/:id', to: 'sales#done', as: 'done'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
class Sale < ApplicationRecord
  validates_uniqueness_of :cod
  validates :detail, presence: true
  validates :category, inclusion: { in: %w(uno dos tres cuatro cinco),
    message: "%{category} is not valid " }
  validates :value, numericality: { only_integer: true , greater_than_or_equal_to: 0}
  validates :discount, numericality: { only_integer: true , greater_than: 0, less_than_or_equal_to: 40}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def new

  end

  def create
    @sale = Sale.new(sale_params)
    @sale.total = @sale.value * (100 - @sale.discount.to_f)/100

    if @sale.tax == 1
      @sale.tax = 19
      @sale.total = @sale.total * ((100 - @sale.tax.to_f)/100)
    else
      @sale.tax = 0
    end

    @sale.save

    redirect_to done_path(@sale)

  end

  def done
    @sale = Sale.find(params[:id])
  end

  private

  def sale_params
    params.require(:sale).permit(:cod, :detail, :category, :value, :discount, :tax)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioFormulariosYValidaciones</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sales/done.html.erb
<h2>El registro fue almacenado con éxito!</h2>

<table style="width:100%">
  <tr>
    <th>Codigo</th>
    <th>Detalle</th>
    <th>Categoria</th>
    <th>Valor Venta</th>
    <th>Descuento</th>
    <th>IVA</th>
    <th>Total final venta</th>
  </tr>
    <tr>
      <th> <%= @sale.cod %> </th>
      <th> <%= @sale.detail %> </th>
      <th> <%= @sale.category %> </th>
      <th> <%= @sale.value %> </th>
      <th> <%= @sale.discount %> </th>
      <th> <%= @sale.tax %> </th>
      <th> <%= @sale.total %> </th>
    </tr>
</table>

<div> <%= link_to "Volver", sales_new_path, class:"btn btn-primary mt-4 ml-4"%> </div>

app/views/sales/new.html.erb
<%= form_with model: Sale.new, local: true do |f| %>
    <%= label_tag 'Codigo' %>
    <%= f.text_field :cod %>
    <%= label_tag 'Detalle' %>
    <%= f.text_field :detail %>
    <%= label_tag 'Category' %>
    <%= f.text_field :category %>
    <%= label_tag 'Value' %>
    <%= f.text_field :value %>
    <%= label_tag 'Descuento' %>
    <%= f.text_field :discount %>
    <%= label_tag 'Excento de IVA' %>
    <%= f.check_box :tax %>
    <%= f.submit "Enviar" %>

<% end %>